// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHmqHNQ2dTfiY2SGdJhrwPm5FXc_V4Rm8',
    appId: '1:317051622533:web:a9a0272bd5ca6fd1cd85ec',
    messagingSenderId: '317051622533',
    projectId: 'app-flutter01-maicon',
    authDomain: 'app-flutter01-maicon.firebaseapp.com',
    storageBucket: 'app-flutter01-maicon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6n9fgSPYCYffmLHXiqfA3Zvn1OJm6wHg',
    appId: '1:317051622533:android:b5e36b1681e0ce72cd85ec',
    messagingSenderId: '317051622533',
    projectId: 'app-flutter01-maicon',
    storageBucket: 'app-flutter01-maicon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoD4tcOIJcpLX_juUSxLpMOGfY7y7hgLc',
    appId: '1:317051622533:ios:b993735b107aac29cd85ec',
    messagingSenderId: '317051622533',
    projectId: 'app-flutter01-maicon',
    storageBucket: 'app-flutter01-maicon.firebasestorage.app',
    iosBundleId: 'com.devmaicon.flutterApplication2',
  );

  DefaultFirebaseOptions(currentPlatform);
}
